/**
 * Template for the bun:sqlite -> Cloudflare D1 shim.
 * This implements the Class-based Database API.
 */

export function getD1DatabaseShim(bindingName: string): string {
  return `
/**
 * Cloudflare D1 Shim for bun:sqlite
 * Generated by bunflare
 */

interface D1Database {
  prepare(query: string): D1PreparedStatement;
}

interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  all<T = unknown>(): Promise<D1Result<T>>;
  run(): Promise<D1Response>;
}

interface D1Result<T = unknown> {
  results: T[];
  success: boolean;
  error?: string;
}

interface D1Response {
  success: boolean;
  error?: string;
}

export class Database {
  private _db: D1Database | null = null;
  private _bindingName: string;
  
  constructor(filename: string = ":memory:") {
    // If the filename is provided, we treat it as a potential binding name
    this._bindingName = filename === ":memory:" ? "${bindingName}" : filename;
  }

  private get db(): D1Database {
    if (this._db) return this._db;
    
    const env = (globalThis as any).Bun?.env;
    const db = env?.[this._bindingName] as D1Database;

    if (!db) {
       // If specifically requested binding not found, try fallback
       const fallback = env?.["${bindingName}"] as D1Database;
       if (fallback) {
         this._db = fallback;
         return fallback;
       }
       throw new Error(\`[bunflare] D1 Binding '\${this._bindingName}' not found in Bun.env.\`);
    }

    this._db = db;
    return db;
  }

  query(sql: string): Statement {
    return new Statement(this.db, sql);
  }

  prepare(sql: string): Statement {
    return new Statement(this.db, sql);
  }

  run(sql: string, ...params: unknown[]): void {
    const bindParams = params.length === 1 && Array.isArray(params[0]) ? params[0] : params;
    return this.db.prepare(sql).bind(...bindParams).run() as any;
  }
}

class Statement {
  constructor(private db: D1Database, private sql: string) {}

  all(...params: unknown[]): unknown[] {
    const bindParams = params.length === 1 && Array.isArray(params[0]) ? params[0] : params;
    return this.db.prepare(this.sql).bind(...bindParams).all() as any;
  }

  get(...params: unknown[]): any {
    throw new Error("bunflare error: 'bun:sqlite' Statement.get() is synchronous. Use 'Bun.sql' instead.");
  }

  run(...params: unknown[]): any {
    const bindParams = params.length === 1 && Array.isArray(params[0]) ? params[0] : params;
    return this.db.prepare(this.sql).bind(...bindParams).run();
  }
}
`;
}
