import { readFileSync } from "fs";
import { join } from "path";

/**
 * Template for the Bun.sql / Bun.SQL -> Cloudflare D1 shim.
 */
export function getSqlTagShim(bindingName: string): string {
  // Read the logic from the standalone file to ensure consistency
  const logicPath = join(import.meta.dir, "logic.ts");
  const logicCode = readFileSync(logicPath, "utf8")
    .replace(/export /g, ""); // Remove export keywords for the shim body

  return `
/**
 * Cloudflare D1 Shim for Bun.sql
 * Generated by bunflare
 */

${logicCode}

export const sql = createSQL("${bindingName}");
export const SQL = class {
  constructor(options?: unknown) {
    return createSQL("${bindingName}") as any; 
  }
};
`;
}
