/**
 * Template for the Bun.crypto / Bun.password -> Web Crypto shim.
 */

export function getCryptoShim(): string {
  return `
/**
 * Web Crypto Shim for Bun.password / Bun.hash
 * Generated by bunflare
 */

export const password = {
  async hash(pw: string): Promise<string> {
    // Bun.password.hash is sync, but we use Web Crypto (async)
    // This is a common pattern for bunflare: shims become async.
    const encoder = new TextEncoder();
    const data = encoder.encode(pw);
    const hashBuffer = await crypto.subtle.digest("SHA-256", data);
    const hashArray = Array.from(new Uint8Array(hashBuffer));
    return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
  },

  async verify(pw: string, hash: string): Promise<boolean> {
    const newHash = await this.hash(pw);
    return newHash === hash;
  }
};

export const hash = async (data: string | ArrayBuffer): Promise<string> => {
  const content = typeof data === "string" ? new TextEncoder().encode(data) : data;
  const hashBuffer = await crypto.subtle.digest("SHA-256", content);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, "0")).join("");
};

// Map global Bun.password to this object
export const BunCrypto = {
  password,
  hash
};
`;
}
