/**
 * bun:sqlite (D1 Bridge)
 * Generated by bunflare
 */

export function getD1DatabaseShim(bindingName: string): string {
  return `
export class Database {
  constructor(path, options) {
    this.bindingName = "${bindingName}";
  }

  query(sql) {
    const bindingName = this.bindingName;
    return {
      all: async (...params) => {
        const binding = (globalThis).Bun?.env?.[bindingName];
        if (!binding) throw new Error(\`Binding "\${bindingName}" not found.\`);
        const res = await binding.prepare(sql).bind(...params).all();
        return res.results;
      },
      get: async (...params) => {
        const binding = (globalThis).Bun?.env?.[bindingName];
        if (!binding) throw new Error(\`Binding "\${bindingName}" not found.\`);
        const res = await binding.prepare(sql).bind(...params).first();
        return res;
      },
      run: async (...params) => {
        const binding = (globalThis).Bun?.env?.[bindingName];
        if (!binding) throw new Error(\`Binding "\${bindingName}" not found.\`);
        return await binding.prepare(sql).bind(...params).run();
      },
      values: async (...params) => {
        const binding = (globalThis).Bun?.env?.[bindingName];
        if (!binding) throw new Error(\`Binding "\${bindingName}" not found.\`);
        const res = await binding.prepare(sql).bind(...params).raw();
        return res;
      }
    };
  }

  prepare(sql) {
    return this.query(sql);
  }

  all(sql, ...params) {
    return this.query(sql).all(...params);
  }

  get(sql, ...params) {
    return this.query(sql).get(...params);
  }

  run(sql, ...params) {
    return this.query(sql).run(...params);
  }

  values(sql, ...params) {
    return this.query(sql).values(...params);
  }

  async exec(sql) {
    const binding = (globalThis).Bun?.env?.[this.bindingName];
    if (!binding) throw new Error(\`Binding "\${this.bindingName}" not found.\`);
    return await binding.exec(sql);
  }

  close() {}
}

export default {
  Database
};
`;
}
