/**
 * Template for the Bun.env shim.
 */

export function getEnvShim(): string {
  return `
/**
 * Env Shim for Bun.env
 * Generated by bunflare
 */

// Use a Proxy to handle access to the environment variables
// This maps Bun.env to the Cloudflare 'env' object injected at runtime.

const envProxy = new Proxy({}, {
  get(_, prop: string) {
    const workerEnv = (globalThis as unknown as { env: Record<string, string | undefined> }).env || {};
    const processEnv = (globalThis as unknown as { process?: { env?: Record<string, string | undefined> } }).process?.env;
    return workerEnv[prop] || processEnv?.[prop];
  }
});

export const env = envProxy as Record<string, string | undefined>;

/**
 * Utility to set the environment object at runtime.
 * In Cloudflare Workers, call this at the start of your fetch handler:
 * BunEnv.setEnv(env);
 */
export function setEnv(newEnv: unknown) {
  (globalThis as unknown as { env: unknown }).env = newEnv;
}

/**
 * Higher-order function to wrap your Cloudflare Worker fetch handler.
 * Automatically calls setEnv(env) for you.
 */
export function withBunflare<E = any>(
  handler: (request: Request, env: E, ctx: unknown) => Response | Promise<Response>
) {
  return {
    async fetch(request: Request, env: E, ctx: unknown) {
      setEnv(env);
      return handler(request, env, ctx);
    }
  };
}
`;
}
