/**
 * Template for the bun:kv -> Cloudflare KV shim.
 */

export function getKvShim(bindingName: string): string {
  return `
/**
 * Cloudflare KV Shim for bun:kv
 * Generated by bunflare
 */

interface KVNamespace {
  get(key: string): Promise<string | null>;
  put(key: string, value: string | ArrayBuffer | ReadableStream): Promise<void>;
  delete(key: string): Promise<void>;
  list(options?: { prefix?: string; limit?: number; cursor?: string }): Promise<{ keys: { name: string }[]; list_complete: boolean; cursor?: string }>;
}

export class KV {
  private kv: KVNamespace;

  constructor() {
    const env = (globalThis as unknown as { env: Record<string, unknown> }).env;
    if (!env || !env["${bindingName}"]) {
      throw new Error("KV Binding '${bindingName}' not found in environment.");
    }
    this.kv = env["${bindingName}"] as KVNamespace;
  }

  async get(key: string): Promise<string | null> {
    return this.kv.get(key);
  }

  async set(key: string, value: string | ArrayBuffer): Promise<void> {
    return this.kv.put(key, value);
  }

  async delete(key: string): Promise<void> {
    return this.kv.delete(key);
  }
}
`;
}
