/**
 * Template for the Bun.redis -> Upstash Redis shim.
 * Uses HTTP as Workers cannot do raw TCP (unless using certain tricks/proxies).
 */

export function getRedisShim(url?: string, token?: string): string {
  return `
/**
 * Upstash Redis Shim for Bun.redis
 * Generated by bunflare
 */

interface UpstashConfig {
  url: string;
  token: string;
}

export class RedisClient {
  private config: UpstashConfig;

  constructor(options?: { url?: string; token?: string }) {
    // Priority: 1. constructor options, 2. plugin options (via generated string), 3. global env
    const env = (globalThis as unknown as { env: Record<string, string | undefined> }).env || {};
    
    this.config = {
      url: options?.url || "${url || ""}" || env.UPSTASH_REDIS_REST_URL || "",
      token: options?.token || "${token || ""}" || env.UPSTASH_REDIS_REST_TOKEN || "",
    };

    if (!this.config.url || !this.config.token) {
      throw new Error("Upstash Redis config missing. Provide url and token in plugin options or UPSTASH_REDIS_REST_* env vars.");
    }
  }

  async get(key: string): Promise<string | null> {
    const res = await fetch(\`\${this.config.url}/get/\${key}\`, {
      headers: { Authorization: \`Bearer \${this.config.token}\` }
    });
    const data = await res.json() as { result: string | null };
    return data.result;
  }

  async set(key: string, value: string): Promise<"OK"> {
    await fetch(\`\${this.config.url}/set/\${key}/\${value}\`, {
      headers: { Authorization: \`Bearer \${this.config.token}\` }
    });
    return "OK";
  }

  // ... implement more of the Bun.RedisClient API
}

// In Bun, Bun.redis is an instance of RedisClient or has a similar interface.
export const redis = new RedisClient();
`;
}
