/**
 * Template for the bun:sqlite -> Cloudflare D1 shim.
 */

export function getSqliteShim(bindingName: string): string {
  return `
/**
 * Cloudflare D1 Shim for bun:sqlite
 * Generated by bunflare
 */

// Define local interfaces for Cloudflare D1 to avoid 'any'
interface D1Database {
  prepare(query: string): D1PreparedStatement;
}

interface D1PreparedStatement {
  bind(...values: unknown[]): D1PreparedStatement;
  all<T = unknown>(): Promise<D1Result<T>>;
  run(): Promise<D1Response>;
}

interface D1Result<T = unknown> {
  results: T[];
  success: boolean;
  error?: string;
}

interface D1Response {
  success: boolean;
  error?: string;
}

interface WorkerEnv {
  [key: string]: unknown;
}

export class Database {
  private db: D1Database;
  
  constructor(filename: string = ":memory:") {
    const env = (globalThis as unknown as { env: WorkerEnv }).env;
    const defaultBinding = "${bindingName}";

    // Check if the filename provided is actually the name of a binding
    if (env && env[filename]) {
      this.db = env[filename] as D1Database;
      return;
    }

    // Fallback to default binding
    if (!env || !env[defaultBinding]) {
      throw new Error(\`D1 Binding '\${defaultBinding}' not found in environment. Check your wrangler.jsonc.\`);
    }
    
    if (filename !== ":memory:") {
      console.warn(\`[bunflare] bun:sqlite: Database filename "\${filename}" not found as a binding. Using default "\${defaultBinding}" instead.\`);
    }

    this.db = env[defaultBinding] as D1Database;
  }

  query(sql: string): Statement {
    return new Statement(this.db, sql);
  }

  run(sql: string, ...params: unknown[]): void {
    // Note: D1 is async, Bun.Sqlite is sync.
    // This will trigger the D1 call but won't wait for it in a sync context.
    this.db.prepare(sql).bind(...params).run().catch(err => {
      console.error("bunflare: D1 run error (async background):", err);
    });
  }
}

class Statement {
  constructor(private db: D1Database, private sql: string) {}

  all(...params: unknown[]): unknown[] {
    // CRITICAL: D1 is async, Bun.Sqlite is sync.
    // There is no clean way to make D1 sync in Workers.
    throw new Error(
      "bunflare error: 'bun:sqlite' Statement.all() is synchronous, but Cloudflare D1 is asynchronous. " +
      "You must refactor your code to use an asynchronous D1 client or wait for bunflare to support async mappings."
    );
  }
}
`;
}
