/**
 * Generates the shim string for Hyperdrive SQL support.
 */
export function getHyperdriveSqlShim(bindingName: string, driver: "postgres" | "mysql2" = "postgres"): string {
  
  // Logic is inlined to avoid file resolution issues in bundled environments
  let logic = `
interface PostgresClient {
  (strings: TemplateStringsArray, ...values: unknown[]): Promise<unknown>;
  unsafe(query: string): Promise<unknown>;
  end(): Promise<void>;
}

function createSQL(bindingName, driver = "postgres") {

  async function executeQuery(queryFn) {
    const global = globalThis;
    const env = global.__BUNFLARE_TEST_ENV__ || global.Bun?.env;
    const hyperdrive = env?.[bindingName];

    if (!hyperdrive || !hyperdrive.connectionString) {
      throw new Error(\`[bunflare] Hyperdrive binding "\${bindingName}" not found in Bun.env\`);
    }

    if (driver === "postgres") {
      const importFn = new Function("m", "return import(m)");
      const { default: postgres } = await importFn("postgres");
      const client = postgres(hyperdrive.connectionString, {
        max: 1,
        onnotice: () => { }
      });
      try {
        return await queryFn(client);
      } finally {
        await client.end();
      }
    } else {
      throw new Error(\`[bunflare] Driver "\${driver}" for Hyperdrive is not yet implemented in Bun.sql shim.\`);
    }
  }

  function sql(strings, ...values) {
    const execute = async () => {
      return executeQuery(async (client) => {
        if (driver === "postgres") {
          return await client(strings, ...values);
        }
      });
    };

    const promise = execute();

    return {
      then: promise.then.bind(promise),
      catch: promise.catch.bind(promise),
      finally: promise.finally.bind(promise),
      async values() {
        const results = await promise;
        if (!results || results.length === 0) return [];
        const keys = Object.keys(results[0]);
        return results.map(row => keys.map(k => row[k]));
      }
    };
  }

  const unsafe = async (str) => {
    return executeQuery(async (client) => {
      if (driver === "postgres") return await client.unsafe(str);
    });
  };

  sql.unsafe = unsafe;
  return sql;
}
`;

  return `
/**
 * Cloudflare Hyperdrive Shim for Bun.sql
 * Generated by bunflare
 */

${logic}

export const sql = createSQL("${bindingName}", "${driver}");
export const SQL = sql;
`;
}
