version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: bunflare_postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: bunflare
    ports:
      - "5433:5432"
