import { readFileSync } from "fs";
import { join } from "path";

/**
 * Generates the shim string for Hyperdrive SQL support.
 */
export function getHyperdriveSqlShim(bindingName: string, driver: "postgres" | "pg" | "mysql2" = "postgres"): string {
  const logicPath = join(import.meta.dir, "logic.ts");
  let logic = readFileSync(logicPath, "utf8");

  // Prevent esbuild from trying to bundle the driver we aren't using.
  // Because logic.ts contains dynamic imports for both, esbuild tries to resolve both.
  // We hide the literal string from static analysis by replacing it.
  if (driver === "postgres") {
    logic = logic.replace(/await import\("pg"\)/g, "undefined /* ignored pg */");
  } else if (driver === "pg") {
    logic = logic.replace(/await import\("postgres"\)/g, "undefined /* ignored postgres */");
  }

  return `
/**
 * Cloudflare Hyperdrive Shim for Bun.sql
 * Generated by bunflare
 */

${logic}

export const sql = createSQL("${bindingName}", "${driver}");
export const SQL = sql;
`;
}
